// Generated by `wit-bindgen` 0.12.0. DO NOT EDIT!
#ifndef __BINDINGS_HTTP_TRIGGER_H
#define __BINDINGS_HTTP_TRIGGER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t*ptr;
  size_t len;
} http_trigger_string_t;

typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t provider;
    http_trigger_string_t invalid_key;
    http_trigger_string_t invalid_schema;
    http_trigger_string_t other;
  } val;
} fermyon_spin_config_error_t;

#define FERMYON_SPIN_CONFIG_ERROR_PROVIDER 0
#define FERMYON_SPIN_CONFIG_ERROR_INVALID_KEY 1
#define FERMYON_SPIN_CONFIG_ERROR_INVALID_SCHEMA 2
#define FERMYON_SPIN_CONFIG_ERROR_OTHER 3

typedef struct {
  bool is_err;
  union {
    http_trigger_string_t ok;
    fermyon_spin_config_error_t err;
  } val;
} http_trigger_result_string_fermyon_spin_config_error_t;

typedef uint16_t fermyon_spin_http_types_http_status_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} fermyon_spin_http_types_body_t;

typedef struct {
  http_trigger_string_t f0;
  http_trigger_string_t f1;
} http_trigger_tuple2_string_string_t;

typedef struct {
  http_trigger_tuple2_string_string_t *ptr;
  size_t len;
} fermyon_spin_http_types_headers_t;

typedef struct {
  http_trigger_tuple2_string_string_t *ptr;
  size_t len;
} fermyon_spin_http_types_params_t;

typedef http_trigger_string_t fermyon_spin_http_types_uri_t;

typedef uint8_t fermyon_spin_http_types_method_t;

#define FERMYON_SPIN_HTTP_TYPES_METHOD_GET 0
#define FERMYON_SPIN_HTTP_TYPES_METHOD_POST 1
#define FERMYON_SPIN_HTTP_TYPES_METHOD_PUT 2
#define FERMYON_SPIN_HTTP_TYPES_METHOD_DELETE 3
#define FERMYON_SPIN_HTTP_TYPES_METHOD_PATCH 4
#define FERMYON_SPIN_HTTP_TYPES_METHOD_HEAD 5
#define FERMYON_SPIN_HTTP_TYPES_METHOD_OPTIONS 6

typedef struct {
  bool is_some;
  fermyon_spin_http_types_body_t val;
} http_trigger_option_fermyon_spin_http_types_body_t;

typedef struct {
  fermyon_spin_http_types_method_t method;
  fermyon_spin_http_types_uri_t uri;
  fermyon_spin_http_types_headers_t headers;
  fermyon_spin_http_types_params_t params;
  http_trigger_option_fermyon_spin_http_types_body_t body;
} fermyon_spin_http_types_request_t;

typedef struct {
  bool is_some;
  fermyon_spin_http_types_headers_t val;
} http_trigger_option_fermyon_spin_http_types_headers_t;

typedef struct {
  fermyon_spin_http_types_http_status_t status;
  http_trigger_option_fermyon_spin_http_types_headers_t headers;
  http_trigger_option_fermyon_spin_http_types_body_t body;
} fermyon_spin_http_types_response_t;

typedef uint8_t fermyon_spin_http_types_http_error_t;

#define FERMYON_SPIN_HTTP_TYPES_HTTP_ERROR_SUCCESS 0
#define FERMYON_SPIN_HTTP_TYPES_HTTP_ERROR_DESTINATION_NOT_ALLOWED 1
#define FERMYON_SPIN_HTTP_TYPES_HTTP_ERROR_INVALID_URL 2
#define FERMYON_SPIN_HTTP_TYPES_HTTP_ERROR_REQUEST_ERROR 3
#define FERMYON_SPIN_HTTP_TYPES_HTTP_ERROR_RUNTIME_ERROR 4
#define FERMYON_SPIN_HTTP_TYPES_HTTP_ERROR_TOO_MANY_REQUESTS 5

typedef fermyon_spin_http_types_request_t fermyon_spin_http_request_t;

typedef fermyon_spin_http_types_response_t fermyon_spin_http_response_t;

typedef fermyon_spin_http_types_http_error_t fermyon_spin_http_http_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_http_response_t ok;
    fermyon_spin_http_http_error_t err;
  } val;
} http_trigger_result_fermyon_spin_http_response_fermyon_spin_http_http_error_t;

typedef fermyon_spin_http_types_request_t fermyon_spin_inbound_http_request_t;

typedef fermyon_spin_http_types_response_t fermyon_spin_inbound_http_response_t;

typedef uint32_t fermyon_spin_key_value_store_t;

typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t io;
  } val;
} fermyon_spin_key_value_error_t;

#define FERMYON_SPIN_KEY_VALUE_ERROR_STORE_TABLE_FULL 0
#define FERMYON_SPIN_KEY_VALUE_ERROR_NO_SUCH_STORE 1
#define FERMYON_SPIN_KEY_VALUE_ERROR_ACCESS_DENIED 2
#define FERMYON_SPIN_KEY_VALUE_ERROR_INVALID_STORE 3
#define FERMYON_SPIN_KEY_VALUE_ERROR_NO_SUCH_KEY 4
#define FERMYON_SPIN_KEY_VALUE_ERROR_IO 5

typedef struct {
  bool is_err;
  union {
    fermyon_spin_key_value_store_t ok;
    fermyon_spin_key_value_error_t err;
  } val;
} http_trigger_result_fermyon_spin_key_value_store_fermyon_spin_key_value_error_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} http_trigger_list_u8_t;

typedef struct {
  bool is_err;
  union {
    http_trigger_list_u8_t ok;
    fermyon_spin_key_value_error_t err;
  } val;
} http_trigger_result_list_u8_fermyon_spin_key_value_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_key_value_error_t err;
  } val;
} http_trigger_result_void_fermyon_spin_key_value_error_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    fermyon_spin_key_value_error_t err;
  } val;
} http_trigger_result_bool_fermyon_spin_key_value_error_t;

typedef struct {
  http_trigger_string_t *ptr;
  size_t len;
} http_trigger_list_string_t;

typedef struct {
  bool is_err;
  union {
    http_trigger_list_string_t ok;
    fermyon_spin_key_value_error_t err;
  } val;
} http_trigger_result_list_string_fermyon_spin_key_value_error_t;

// A Large Language Model.
typedef http_trigger_string_t fermyon_spin_llm_inferencing_model_t;

// Inference request parameters
typedef struct {
  // The maximum tokens that should be inferred.
  // 
  // Note: the backing implementation may return less tokens.
  uint32_t max_tokens;
  // The amount the model should avoid repeating tokens.
  float repeat_penalty;
  // The number of tokens the model should apply the repeat penalty to.
  uint32_t repeat_penalty_last_n_token_count;
  // The randomness with which the next token is selected.
  float temperature;
  // The number of possible next tokens the model will choose from.
  uint32_t top_k;
  // The probability total of next tokens the model will choose from.
  float top_p;
} fermyon_spin_llm_inferencing_params_t;

// The set of errors which may be raised by functions in this interface
typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t runtime_error;
    http_trigger_string_t invalid_input;
  } val;
} fermyon_spin_llm_error_t;

#define FERMYON_SPIN_LLM_ERROR_MODEL_NOT_SUPPORTED 0
#define FERMYON_SPIN_LLM_ERROR_RUNTIME_ERROR 1
#define FERMYON_SPIN_LLM_ERROR_INVALID_INPUT 2

// Usage information related to the inferencing result
typedef struct {
  // Number of tokens in the prompt
  uint32_t prompt_token_count;
  // Number of tokens generated by the inferencing operation
  uint32_t generated_token_count;
} fermyon_spin_llm_inferencing_usage_t;

// An inferencing result
typedef struct {
  // The text generated by the model
  http_trigger_string_t text;
  // Usage information about the inferencing request
  fermyon_spin_llm_inferencing_usage_t usage;
} fermyon_spin_llm_inferencing_result_t;

// The model used for generating embeddings
typedef http_trigger_string_t fermyon_spin_llm_embedding_model_t;

// Usage related to an embeddings generation request
typedef struct {
  // Number of tokens in the prompt
  uint32_t prompt_token_count;
} fermyon_spin_llm_embeddings_usage_t;

typedef struct {
  float *ptr;
  size_t len;
} http_trigger_list_float32_t;

typedef struct {
  http_trigger_list_float32_t *ptr;
  size_t len;
} http_trigger_list_list_float32_t;

// Result of generating embeddings
typedef struct {
  // The embeddings generated by the request
  http_trigger_list_list_float32_t embeddings;
  // Usage related to the embeddings generation request
  fermyon_spin_llm_embeddings_usage_t usage;
} fermyon_spin_llm_embeddings_result_t;

typedef struct {
  bool is_some;
  fermyon_spin_llm_inferencing_params_t val;
} http_trigger_option_fermyon_spin_llm_inferencing_params_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_llm_inferencing_result_t ok;
    fermyon_spin_llm_error_t err;
  } val;
} http_trigger_result_fermyon_spin_llm_inferencing_result_fermyon_spin_llm_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_llm_embeddings_result_t ok;
    fermyon_spin_llm_error_t err;
  } val;
} http_trigger_result_fermyon_spin_llm_embeddings_result_fermyon_spin_llm_error_t;

typedef uint8_t fermyon_spin_rdbms_types_db_data_type_t;

#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_BOOLEAN 0
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_INT8 1
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_INT16 2
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_INT32 3
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_INT64 4
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_UINT8 5
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_UINT16 6
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_UINT32 7
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_UINT64 8
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_FLOATING32 9
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_FLOATING64 10
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_STR 11
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_BINARY 12
#define FERMYON_SPIN_RDBMS_TYPES_DB_DATA_TYPE_OTHER 13

typedef struct {
  uint8_t tag;
  union {
    bool boolean;
    int8_t int8;
    int16_t int16;
    int32_t int32;
    int64_t int64;
    uint8_t uint8;
    uint16_t uint16;
    uint32_t uint32;
    uint64_t uint64;
    float floating32;
    double floating64;
    http_trigger_string_t str;
    http_trigger_list_u8_t binary;
  } val;
} fermyon_spin_rdbms_types_db_value_t;

#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_BOOLEAN 0
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_INT8 1
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_INT16 2
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_INT32 3
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_INT64 4
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_UINT8 5
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_UINT16 6
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_UINT32 7
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_UINT64 8
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_FLOATING32 9
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_FLOATING64 10
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_STR 11
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_BINARY 12
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_DB_NULL 13
#define FERMYON_SPIN_RDBMS_TYPES_DB_VALUE_UNSUPPORTED 14

typedef struct {
  uint8_t tag;
  union {
    bool boolean;
    int8_t int8;
    int16_t int16;
    int32_t int32;
    int64_t int64;
    uint8_t uint8;
    uint16_t uint16;
    uint32_t uint32;
    uint64_t uint64;
    float floating32;
    double floating64;
    http_trigger_string_t str;
    http_trigger_list_u8_t binary;
  } val;
} fermyon_spin_rdbms_types_parameter_value_t;

#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_BOOLEAN 0
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_INT8 1
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_INT16 2
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_INT32 3
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_INT64 4
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_UINT8 5
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_UINT16 6
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_UINT32 7
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_UINT64 8
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_FLOATING32 9
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_FLOATING64 10
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_STR 11
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_BINARY 12
#define FERMYON_SPIN_RDBMS_TYPES_PARAMETER_VALUE_DB_NULL 13

typedef struct {
  http_trigger_string_t name;
  fermyon_spin_rdbms_types_db_data_type_t data_type;
} fermyon_spin_rdbms_types_column_t;

typedef struct {
  fermyon_spin_rdbms_types_db_value_t *ptr;
  size_t len;
} fermyon_spin_rdbms_types_row_t;

typedef struct {
  fermyon_spin_rdbms_types_column_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_rdbms_types_column_t;

typedef struct {
  fermyon_spin_rdbms_types_row_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_rdbms_types_row_t;

typedef struct {
  http_trigger_list_fermyon_spin_rdbms_types_column_t columns;
  http_trigger_list_fermyon_spin_rdbms_types_row_t rows;
} fermyon_spin_rdbms_types_row_set_t;

typedef fermyon_spin_rdbms_types_parameter_value_t fermyon_spin_mysql_parameter_value_t;

typedef fermyon_spin_rdbms_types_row_set_t fermyon_spin_mysql_row_set_t;

typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t connection_failed;
    http_trigger_string_t bad_parameter;
    http_trigger_string_t query_failed;
    http_trigger_string_t value_conversion_failed;
    http_trigger_string_t other_error;
  } val;
} fermyon_spin_mysql_mysql_error_t;

#define FERMYON_SPIN_MYSQL_MYSQL_ERROR_SUCCESS 0
#define FERMYON_SPIN_MYSQL_MYSQL_ERROR_CONNECTION_FAILED 1
#define FERMYON_SPIN_MYSQL_MYSQL_ERROR_BAD_PARAMETER 2
#define FERMYON_SPIN_MYSQL_MYSQL_ERROR_QUERY_FAILED 3
#define FERMYON_SPIN_MYSQL_MYSQL_ERROR_VALUE_CONVERSION_FAILED 4
#define FERMYON_SPIN_MYSQL_MYSQL_ERROR_OTHER_ERROR 5

typedef struct {
  fermyon_spin_mysql_parameter_value_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_mysql_parameter_value_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_mysql_row_set_t ok;
    fermyon_spin_mysql_mysql_error_t err;
  } val;
} http_trigger_result_fermyon_spin_mysql_row_set_fermyon_spin_mysql_mysql_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_mysql_mysql_error_t err;
  } val;
} http_trigger_result_void_fermyon_spin_mysql_mysql_error_t;

typedef fermyon_spin_rdbms_types_parameter_value_t fermyon_spin_postgres_parameter_value_t;

typedef fermyon_spin_rdbms_types_row_set_t fermyon_spin_postgres_row_set_t;

typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t connection_failed;
    http_trigger_string_t bad_parameter;
    http_trigger_string_t query_failed;
    http_trigger_string_t value_conversion_failed;
    http_trigger_string_t other_error;
  } val;
} fermyon_spin_postgres_pg_error_t;

#define FERMYON_SPIN_POSTGRES_PG_ERROR_SUCCESS 0
#define FERMYON_SPIN_POSTGRES_PG_ERROR_CONNECTION_FAILED 1
#define FERMYON_SPIN_POSTGRES_PG_ERROR_BAD_PARAMETER 2
#define FERMYON_SPIN_POSTGRES_PG_ERROR_QUERY_FAILED 3
#define FERMYON_SPIN_POSTGRES_PG_ERROR_VALUE_CONVERSION_FAILED 4
#define FERMYON_SPIN_POSTGRES_PG_ERROR_OTHER_ERROR 5

typedef struct {
  fermyon_spin_postgres_parameter_value_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_postgres_parameter_value_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_postgres_row_set_t ok;
    fermyon_spin_postgres_pg_error_t err;
  } val;
} http_trigger_result_fermyon_spin_postgres_row_set_fermyon_spin_postgres_pg_error_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    fermyon_spin_postgres_pg_error_t err;
  } val;
} http_trigger_result_u64_fermyon_spin_postgres_pg_error_t;

typedef uint8_t fermyon_spin_redis_types_error_t;

#define FERMYON_SPIN_REDIS_TYPES_ERROR_SUCCESS 0
#define FERMYON_SPIN_REDIS_TYPES_ERROR_ERROR 1

typedef struct {
  uint8_t *ptr;
  size_t len;
} fermyon_spin_redis_types_payload_t;

typedef struct {
  uint8_t tag;
  union {
    int64_t int64;
    fermyon_spin_redis_types_payload_t binary;
  } val;
} fermyon_spin_redis_types_redis_parameter_t;

#define FERMYON_SPIN_REDIS_TYPES_REDIS_PARAMETER_INT64 0
#define FERMYON_SPIN_REDIS_TYPES_REDIS_PARAMETER_BINARY 1

typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t status;
    int64_t int64;
    fermyon_spin_redis_types_payload_t binary;
  } val;
} fermyon_spin_redis_types_redis_result_t;

#define FERMYON_SPIN_REDIS_TYPES_REDIS_RESULT_NIL 0
#define FERMYON_SPIN_REDIS_TYPES_REDIS_RESULT_STATUS 1
#define FERMYON_SPIN_REDIS_TYPES_REDIS_RESULT_INT64 2
#define FERMYON_SPIN_REDIS_TYPES_REDIS_RESULT_BINARY 3

typedef fermyon_spin_redis_types_payload_t fermyon_spin_redis_payload_t;

typedef fermyon_spin_redis_types_redis_parameter_t fermyon_spin_redis_redis_parameter_t;

typedef fermyon_spin_redis_types_redis_result_t fermyon_spin_redis_redis_result_t;

typedef fermyon_spin_redis_types_error_t fermyon_spin_redis_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_redis_error_t err;
  } val;
} http_trigger_result_void_fermyon_spin_redis_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_redis_payload_t ok;
    fermyon_spin_redis_error_t err;
  } val;
} http_trigger_result_fermyon_spin_redis_payload_fermyon_spin_redis_error_t;

typedef struct {
  bool is_err;
  union {
    int64_t ok;
    fermyon_spin_redis_error_t err;
  } val;
} http_trigger_result_s64_fermyon_spin_redis_error_t;

typedef struct {
  bool is_err;
  union {
    http_trigger_list_string_t ok;
    fermyon_spin_redis_error_t err;
  } val;
} http_trigger_result_list_string_fermyon_spin_redis_error_t;

typedef struct {
  fermyon_spin_redis_redis_parameter_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_redis_redis_parameter_t;

typedef struct {
  fermyon_spin_redis_redis_result_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_redis_redis_result_t;

typedef struct {
  bool is_err;
  union {
    http_trigger_list_fermyon_spin_redis_redis_result_t ok;
    fermyon_spin_redis_error_t err;
  } val;
} http_trigger_result_list_fermyon_spin_redis_redis_result_fermyon_spin_redis_error_t;

typedef uint32_t fermyon_spin_sqlite_connection_t;

typedef struct {
  uint8_t tag;
  union {
    http_trigger_string_t io;
  } val;
} fermyon_spin_sqlite_error_t;

#define FERMYON_SPIN_SQLITE_ERROR_NO_SUCH_DATABASE 0
#define FERMYON_SPIN_SQLITE_ERROR_ACCESS_DENIED 1
#define FERMYON_SPIN_SQLITE_ERROR_INVALID_CONNECTION 2
#define FERMYON_SPIN_SQLITE_ERROR_DATABASE_FULL 3
#define FERMYON_SPIN_SQLITE_ERROR_IO 4

typedef struct {
  uint8_t tag;
  union {
    int64_t integer;
    double real;
    http_trigger_string_t text;
    http_trigger_list_u8_t blob;
  } val;
} fermyon_spin_sqlite_value_t;

#define FERMYON_SPIN_SQLITE_VALUE_INTEGER 0
#define FERMYON_SPIN_SQLITE_VALUE_REAL 1
#define FERMYON_SPIN_SQLITE_VALUE_TEXT 2
#define FERMYON_SPIN_SQLITE_VALUE_BLOB 3
#define FERMYON_SPIN_SQLITE_VALUE_NULL 4

typedef struct {
  fermyon_spin_sqlite_value_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_sqlite_value_t;

typedef struct {
  http_trigger_list_fermyon_spin_sqlite_value_t values;
} fermyon_spin_sqlite_row_result_t;

typedef struct {
  fermyon_spin_sqlite_row_result_t *ptr;
  size_t len;
} http_trigger_list_fermyon_spin_sqlite_row_result_t;

typedef struct {
  http_trigger_list_string_t columns;
  http_trigger_list_fermyon_spin_sqlite_row_result_t rows;
} fermyon_spin_sqlite_query_result_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_sqlite_connection_t ok;
    fermyon_spin_sqlite_error_t err;
  } val;
} http_trigger_result_fermyon_spin_sqlite_connection_fermyon_spin_sqlite_error_t;

typedef struct {
  bool is_err;
  union {
    fermyon_spin_sqlite_query_result_t ok;
    fermyon_spin_sqlite_error_t err;
  } val;
} http_trigger_result_fermyon_spin_sqlite_query_result_fermyon_spin_sqlite_error_t;

// Imported Functions from `fermyon:spin/config`
extern void fermyon_spin_config_get_config(http_trigger_string_t *key, http_trigger_result_string_fermyon_spin_config_error_t *ret);

// Imported Functions from `fermyon:spin/postgres`
extern void fermyon_spin_postgres_query(http_trigger_string_t *address, http_trigger_string_t *statement, http_trigger_list_fermyon_spin_postgres_parameter_value_t *params, http_trigger_result_fermyon_spin_postgres_row_set_fermyon_spin_postgres_pg_error_t *ret);
extern void fermyon_spin_postgres_execute(http_trigger_string_t *address, http_trigger_string_t *statement, http_trigger_list_fermyon_spin_postgres_parameter_value_t *params, http_trigger_result_u64_fermyon_spin_postgres_pg_error_t *ret);

// Imported Functions from `fermyon:spin/mysql`
extern void fermyon_spin_mysql_query(http_trigger_string_t *address, http_trigger_string_t *statement, http_trigger_list_fermyon_spin_mysql_parameter_value_t *params, http_trigger_result_fermyon_spin_mysql_row_set_fermyon_spin_mysql_mysql_error_t *ret);
extern void fermyon_spin_mysql_execute(http_trigger_string_t *address, http_trigger_string_t *statement, http_trigger_list_fermyon_spin_mysql_parameter_value_t *params, http_trigger_result_void_fermyon_spin_mysql_mysql_error_t *ret);

// Imported Functions from `fermyon:spin/sqlite`
extern void fermyon_spin_sqlite_open(http_trigger_string_t *database, http_trigger_result_fermyon_spin_sqlite_connection_fermyon_spin_sqlite_error_t *ret);
extern void fermyon_spin_sqlite_execute(fermyon_spin_sqlite_connection_t conn, http_trigger_string_t *statement, http_trigger_list_fermyon_spin_sqlite_value_t *parameters, http_trigger_result_fermyon_spin_sqlite_query_result_fermyon_spin_sqlite_error_t *ret);
extern void fermyon_spin_sqlite_close(fermyon_spin_sqlite_connection_t conn);

// Imported Functions from `fermyon:spin/redis`
extern void fermyon_spin_redis_publish(http_trigger_string_t *address, http_trigger_string_t *channel, fermyon_spin_redis_payload_t *payload, http_trigger_result_void_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_get(http_trigger_string_t *address, http_trigger_string_t *key, http_trigger_result_fermyon_spin_redis_payload_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_set(http_trigger_string_t *address, http_trigger_string_t *key, fermyon_spin_redis_payload_t *value, http_trigger_result_void_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_incr(http_trigger_string_t *address, http_trigger_string_t *key, http_trigger_result_s64_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_del(http_trigger_string_t *address, http_trigger_list_string_t *keys, http_trigger_result_s64_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_sadd(http_trigger_string_t *address, http_trigger_string_t *key, http_trigger_list_string_t *values, http_trigger_result_s64_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_smembers(http_trigger_string_t *address, http_trigger_string_t *key, http_trigger_result_list_string_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_srem(http_trigger_string_t *address, http_trigger_string_t *key, http_trigger_list_string_t *values, http_trigger_result_s64_fermyon_spin_redis_error_t *ret);
extern void fermyon_spin_redis_execute(http_trigger_string_t *address, http_trigger_string_t *command, http_trigger_list_fermyon_spin_redis_redis_parameter_t *arguments, http_trigger_result_list_fermyon_spin_redis_redis_result_fermyon_spin_redis_error_t *ret);

// Imported Functions from `fermyon:spin/key-value`
extern void fermyon_spin_key_value_open(http_trigger_string_t *name, http_trigger_result_fermyon_spin_key_value_store_fermyon_spin_key_value_error_t *ret);
extern void fermyon_spin_key_value_get(fermyon_spin_key_value_store_t store, http_trigger_string_t *key, http_trigger_result_list_u8_fermyon_spin_key_value_error_t *ret);
extern void fermyon_spin_key_value_set(fermyon_spin_key_value_store_t store, http_trigger_string_t *key, http_trigger_list_u8_t *value, http_trigger_result_void_fermyon_spin_key_value_error_t *ret);
extern void fermyon_spin_key_value_delete(fermyon_spin_key_value_store_t store, http_trigger_string_t *key, http_trigger_result_void_fermyon_spin_key_value_error_t *ret);
extern void fermyon_spin_key_value_exists(fermyon_spin_key_value_store_t store, http_trigger_string_t *key, http_trigger_result_bool_fermyon_spin_key_value_error_t *ret);
extern void fermyon_spin_key_value_get_keys(fermyon_spin_key_value_store_t store, http_trigger_result_list_string_fermyon_spin_key_value_error_t *ret);
extern void fermyon_spin_key_value_close(fermyon_spin_key_value_store_t store);

// Imported Functions from `fermyon:spin/http`
extern void fermyon_spin_http_send_request(fermyon_spin_http_request_t *req, http_trigger_result_fermyon_spin_http_response_fermyon_spin_http_http_error_t *ret);

// Imported Functions from `fermyon:spin/llm`
// Perform inferencing using the provided model and prompt with the given optional params
extern void fermyon_spin_llm_infer(fermyon_spin_llm_inferencing_model_t *model, http_trigger_string_t *prompt, http_trigger_option_fermyon_spin_llm_inferencing_params_t *params, http_trigger_result_fermyon_spin_llm_inferencing_result_fermyon_spin_llm_error_t *ret);
// Generate embeddings for the supplied list of text
extern void fermyon_spin_llm_generate_embeddings(fermyon_spin_llm_embedding_model_t *model, http_trigger_list_string_t *text, http_trigger_result_fermyon_spin_llm_embeddings_result_fermyon_spin_llm_error_t *ret);

// Exported Functions from `fermyon:spin/inbound-http`
void exports_fermyon_spin_inbound_http_handle_request(fermyon_spin_inbound_http_request_t *req, fermyon_spin_inbound_http_response_t *ret);

// Helper Functions

void fermyon_spin_config_error_free(fermyon_spin_config_error_t *ptr);
void http_trigger_result_string_fermyon_spin_config_error_free(http_trigger_result_string_fermyon_spin_config_error_t *ptr);
void fermyon_spin_http_types_body_free(fermyon_spin_http_types_body_t *ptr);
void http_trigger_tuple2_string_string_free(http_trigger_tuple2_string_string_t *ptr);
void fermyon_spin_http_types_headers_free(fermyon_spin_http_types_headers_t *ptr);
void fermyon_spin_http_types_params_free(fermyon_spin_http_types_params_t *ptr);
void fermyon_spin_http_types_uri_free(fermyon_spin_http_types_uri_t *ptr);
void http_trigger_option_fermyon_spin_http_types_body_free(http_trigger_option_fermyon_spin_http_types_body_t *ptr);
void fermyon_spin_http_types_request_free(fermyon_spin_http_types_request_t *ptr);
void http_trigger_option_fermyon_spin_http_types_headers_free(http_trigger_option_fermyon_spin_http_types_headers_t *ptr);
void fermyon_spin_http_types_response_free(fermyon_spin_http_types_response_t *ptr);
void fermyon_spin_http_request_free(fermyon_spin_http_request_t *ptr);
void fermyon_spin_http_response_free(fermyon_spin_http_response_t *ptr);
void http_trigger_result_fermyon_spin_http_response_fermyon_spin_http_http_error_free(http_trigger_result_fermyon_spin_http_response_fermyon_spin_http_http_error_t *ptr);
void fermyon_spin_inbound_http_request_free(fermyon_spin_inbound_http_request_t *ptr);
void fermyon_spin_inbound_http_response_free(fermyon_spin_inbound_http_response_t *ptr);
void fermyon_spin_key_value_error_free(fermyon_spin_key_value_error_t *ptr);
void http_trigger_result_fermyon_spin_key_value_store_fermyon_spin_key_value_error_free(http_trigger_result_fermyon_spin_key_value_store_fermyon_spin_key_value_error_t *ptr);
void http_trigger_list_u8_free(http_trigger_list_u8_t *ptr);
void http_trigger_result_list_u8_fermyon_spin_key_value_error_free(http_trigger_result_list_u8_fermyon_spin_key_value_error_t *ptr);
void http_trigger_result_void_fermyon_spin_key_value_error_free(http_trigger_result_void_fermyon_spin_key_value_error_t *ptr);
void http_trigger_result_bool_fermyon_spin_key_value_error_free(http_trigger_result_bool_fermyon_spin_key_value_error_t *ptr);
void http_trigger_list_string_free(http_trigger_list_string_t *ptr);
void http_trigger_result_list_string_fermyon_spin_key_value_error_free(http_trigger_result_list_string_fermyon_spin_key_value_error_t *ptr);
void fermyon_spin_llm_inferencing_model_free(fermyon_spin_llm_inferencing_model_t *ptr);
void fermyon_spin_llm_error_free(fermyon_spin_llm_error_t *ptr);
void fermyon_spin_llm_inferencing_result_free(fermyon_spin_llm_inferencing_result_t *ptr);
void fermyon_spin_llm_embedding_model_free(fermyon_spin_llm_embedding_model_t *ptr);
void http_trigger_list_float32_free(http_trigger_list_float32_t *ptr);
void http_trigger_list_list_float32_free(http_trigger_list_list_float32_t *ptr);
void fermyon_spin_llm_embeddings_result_free(fermyon_spin_llm_embeddings_result_t *ptr);
void http_trigger_result_fermyon_spin_llm_inferencing_result_fermyon_spin_llm_error_free(http_trigger_result_fermyon_spin_llm_inferencing_result_fermyon_spin_llm_error_t *ptr);
void http_trigger_result_fermyon_spin_llm_embeddings_result_fermyon_spin_llm_error_free(http_trigger_result_fermyon_spin_llm_embeddings_result_fermyon_spin_llm_error_t *ptr);
void fermyon_spin_rdbms_types_db_value_free(fermyon_spin_rdbms_types_db_value_t *ptr);
void fermyon_spin_rdbms_types_parameter_value_free(fermyon_spin_rdbms_types_parameter_value_t *ptr);
void fermyon_spin_rdbms_types_column_free(fermyon_spin_rdbms_types_column_t *ptr);
void fermyon_spin_rdbms_types_row_free(fermyon_spin_rdbms_types_row_t *ptr);
void http_trigger_list_fermyon_spin_rdbms_types_column_free(http_trigger_list_fermyon_spin_rdbms_types_column_t *ptr);
void http_trigger_list_fermyon_spin_rdbms_types_row_free(http_trigger_list_fermyon_spin_rdbms_types_row_t *ptr);
void fermyon_spin_rdbms_types_row_set_free(fermyon_spin_rdbms_types_row_set_t *ptr);
void fermyon_spin_mysql_parameter_value_free(fermyon_spin_mysql_parameter_value_t *ptr);
void fermyon_spin_mysql_row_set_free(fermyon_spin_mysql_row_set_t *ptr);
void fermyon_spin_mysql_mysql_error_free(fermyon_spin_mysql_mysql_error_t *ptr);
void http_trigger_list_fermyon_spin_mysql_parameter_value_free(http_trigger_list_fermyon_spin_mysql_parameter_value_t *ptr);
void http_trigger_result_fermyon_spin_mysql_row_set_fermyon_spin_mysql_mysql_error_free(http_trigger_result_fermyon_spin_mysql_row_set_fermyon_spin_mysql_mysql_error_t *ptr);
void http_trigger_result_void_fermyon_spin_mysql_mysql_error_free(http_trigger_result_void_fermyon_spin_mysql_mysql_error_t *ptr);
void fermyon_spin_postgres_parameter_value_free(fermyon_spin_postgres_parameter_value_t *ptr);
void fermyon_spin_postgres_row_set_free(fermyon_spin_postgres_row_set_t *ptr);
void fermyon_spin_postgres_pg_error_free(fermyon_spin_postgres_pg_error_t *ptr);
void http_trigger_list_fermyon_spin_postgres_parameter_value_free(http_trigger_list_fermyon_spin_postgres_parameter_value_t *ptr);
void http_trigger_result_fermyon_spin_postgres_row_set_fermyon_spin_postgres_pg_error_free(http_trigger_result_fermyon_spin_postgres_row_set_fermyon_spin_postgres_pg_error_t *ptr);
void http_trigger_result_u64_fermyon_spin_postgres_pg_error_free(http_trigger_result_u64_fermyon_spin_postgres_pg_error_t *ptr);
void fermyon_spin_redis_types_payload_free(fermyon_spin_redis_types_payload_t *ptr);
void fermyon_spin_redis_types_redis_parameter_free(fermyon_spin_redis_types_redis_parameter_t *ptr);
void fermyon_spin_redis_types_redis_result_free(fermyon_spin_redis_types_redis_result_t *ptr);
void fermyon_spin_redis_payload_free(fermyon_spin_redis_payload_t *ptr);
void fermyon_spin_redis_redis_parameter_free(fermyon_spin_redis_redis_parameter_t *ptr);
void fermyon_spin_redis_redis_result_free(fermyon_spin_redis_redis_result_t *ptr);
void http_trigger_result_fermyon_spin_redis_payload_fermyon_spin_redis_error_free(http_trigger_result_fermyon_spin_redis_payload_fermyon_spin_redis_error_t *ptr);
void http_trigger_result_list_string_fermyon_spin_redis_error_free(http_trigger_result_list_string_fermyon_spin_redis_error_t *ptr);
void http_trigger_list_fermyon_spin_redis_redis_parameter_free(http_trigger_list_fermyon_spin_redis_redis_parameter_t *ptr);
void http_trigger_list_fermyon_spin_redis_redis_result_free(http_trigger_list_fermyon_spin_redis_redis_result_t *ptr);
void http_trigger_result_list_fermyon_spin_redis_redis_result_fermyon_spin_redis_error_free(http_trigger_result_list_fermyon_spin_redis_redis_result_fermyon_spin_redis_error_t *ptr);
void fermyon_spin_sqlite_error_free(fermyon_spin_sqlite_error_t *ptr);
void fermyon_spin_sqlite_value_free(fermyon_spin_sqlite_value_t *ptr);
void http_trigger_list_fermyon_spin_sqlite_value_free(http_trigger_list_fermyon_spin_sqlite_value_t *ptr);
void fermyon_spin_sqlite_row_result_free(fermyon_spin_sqlite_row_result_t *ptr);
void http_trigger_list_fermyon_spin_sqlite_row_result_free(http_trigger_list_fermyon_spin_sqlite_row_result_t *ptr);
void fermyon_spin_sqlite_query_result_free(fermyon_spin_sqlite_query_result_t *ptr);
void http_trigger_result_fermyon_spin_sqlite_connection_fermyon_spin_sqlite_error_free(http_trigger_result_fermyon_spin_sqlite_connection_fermyon_spin_sqlite_error_t *ptr);
void http_trigger_result_fermyon_spin_sqlite_query_result_fermyon_spin_sqlite_error_free(http_trigger_result_fermyon_spin_sqlite_query_result_fermyon_spin_sqlite_error_t *ptr);
// Transfers ownership of `s` into the string `ret`
void http_trigger_string_set(http_trigger_string_t *ret, char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void http_trigger_string_dup(http_trigger_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void http_trigger_string_free(http_trigger_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
